### ISSUE TITLE
[links] Identical links within footer 

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/OR-UK-frontend#158]
URL: https://openreferraluk.org/

The links "Open data standards" and "Why use the standard" have identical links. Should "Why use the standard" link to the heading 3? https://openreferraluk.org/about-standard#section-3-heading

**Comment by kingdomlevel** [comment]
Possibly related to #98

**Comment by kingdomlevel** [comment]
CMS fix for what can be done for now, linking to the standard as suggested by @UsmanAfzal

**Comment by UsmanAfzal** [comment]
Checked and approved
