### ISSUE TITLE
[validation] Main role is unnecessary for element <main>

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/OR-UK-frontend#169]
URL: https://openreferraluk.org/

The main role is unnecessary for element main.
`<main id="content" class="main-container" role="main">`

**Comment by adamgparsons** [comment]
Depends on #209 as it's a dashboard fix

**Comment by kingdomlevel** [comment]
PR #209 has now been merged - removing the 'blocked' label and moving to 'To Do'

**Comment by UsmanAfzal** [comment]
Checked and approved
