### ISSUE TITLE
[content flash] Flash of content "404 - content not found!"

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/OR-UK-frontend#171]
URL: https://openreferraluk.org/community/case-studies

When landing on the page users see a flash of content "404 - content not found!". This occurs for every refresh.

https://user-images.githubusercontent.com/2459151/123019473-74b6f780-d3c8-11eb-8274-35fcc13ea220.mov

**Comment by kingdomlevel** [comment]
Will be closed by #209 

[Specific code that fixes this](https://github.com/WeAreSnook/OR-UK-frontend/pull/209/files#r672177636)

**Comment by UsmanAfzal** [comment]
Checked and approved
