### ISSUE TITLE
It is unclear for screenreader users what they are registering for

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/OR-UK-frontend#173]
URL: 
https://openreferraluk.org/
https://openreferraluk.org/standard-community

On the homepage it is unclear to users of screen readers what they are registering for, potentially even other users. The language seems to imply they are registering to use open referral, when in fact it is just to feature themselves on the website.

Screenreader users currently hear:
1. Organisations using Open Referral UK
2. 6 considering, 4 adopting, 6 adopted
3. Register now

It would be much more understandable if it were to say:
1. Organisations using Open Referral UK
2. 6 considering, 4 adopting 6 adopted
3. Feature your organisation

<img width="754" alt="Screenshot 2021-06-23 at 16 36 59" src="https://user-images.githubusercontent.com/2459151/123126385-3f9abb80-d441-11eb-9ef7-fa3af853534b.png">

**Comment by adamgparsons** [comment]
Hey @kingdomlevel. This looks look a change we could make in the CMS. Would you be able to take a look?

**Comment by UsmanAfzal** [comment]
Checked and updated
