### ISSUE TITLE
[headings] heading level 4 proceeding a heading level 2

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/OR-UK-frontend#178]
URL: https://openreferraluk.org/how-it-works/standard-adoption-steps

Under "how it works" > "Steps to adopting the standard", heading level 4s are proceeding all headings at level 2.

Example:
<img width="1138" alt="Screenshot 2021-06-23 at 17 54 51" src="https://user-images.githubusercontent.com/2459151/123137945-70342280-d44c-11eb-8cc0-6fb6e1ed7e7d.png">

**Comment by kingdomlevel** [comment]
Content change - updated to reflect the correct heading structure.

**Comment by UsmanAfzal** [comment]
Checked and approved
