### ISSUE TITLE
[link] Focus state for links within cookie component do not have sufficient contrast

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/OR-UK-frontend#181]
URL: https://openreferraluk.org/privacy-policy

Focus state for links within cookie component do not have sufficient contrast. Focus states for:

- Reject analytics cookies
- View cookies

Need to use the same focus state as applied within the footer as that also has a dark green background.

**Focus applied to View cookies**
![Screenshot 2021-06-28 at 14 53 28](https://user-images.githubusercontent.com/2459151/123650762-ccb78900-d822-11eb-9920-a654d62a788d.png)

**Focus applied to Reject analytics cookies**
![Screenshot 2021-06-28 at 14 53 36](https://user-images.githubusercontent.com/2459151/123650786-d04b1000-d822-11eb-8616-3cd90c0ce922.png)

**Comment by kingdomlevel** [comment]
Blocked by #209 as this is a fix around the cookie implementation for Google Analytics. Will revisit once this merges!

**Comment by kingdomlevel** [comment]
PR #209 has now been merged - removing the 'blocked' label and moving to 'To Do'

**Comment by UsmanAfzal** [comment]
Checked and approved
