### ISSUE TITLE
[icon] The back icon is broken

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/OR-UK-frontend#184]
URL: https://openreferraluk.org/community/case-studies

The back button with icon is not rendering correctly. This was not present previously but has occurred recently.

<img width="829" alt="Screenshot 2021-06-28 at 17 29 38" src="https://user-images.githubusercontent.com/2459151/123671867-a3a0f380-d836-11eb-9327-2a285d25258a.png">

**Comment by adamgparsons** [comment]
Hey @UsmanAfzal. I have tested this on different browsers on my machine and can't reproduce the problem. Would you happen to know what browser you used to produce this error?

**Comment by UsmanAfzal** [comment]
Hi @adamgparsons it was on Firefox but seems to have resolved itself.

**Comment by kingdomlevel** [comment]
Thanks Mozilla! 🙌 

 Lol - I'll move this to done but please feel free to re-open if anyone is not satisfied.
