### ISSUE TITLE
[modal] Modal is offset from small device screens

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/OR-UK-frontend#187]
URL: https://openreferraluk.org/dashboard

To make the content easier to read and control when displayed on small screens, the modal should fill 100% of the screen. Completely covering the background also hides background movement that occurs on some mobile devices when scrolling content inside the dialog.

**Current modal on mobile devices:**
<img width="309" alt="Screenshot 2021-06-29 at 14 58 10" src="https://user-images.githubusercontent.com/2459151/123810573-6d24b080-d8ea-11eb-86e9-7f36e771c66d.png">

**Comment by kingdomlevel** [comment]
Fix to the Dashboard page - depends on #209 being merged

**Comment by UsmanAfzal** [comment]
Checked and approved
