### ISSUE TITLE
[modal] Hidden close button accessible with keyboard navigation

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/OR-UK-frontend#188]
URL: https://openreferraluk.org/dashboard

The dashboard has a read button that visually displays a modal when clicked.

**Example**
<img width="652" alt="Screenshot 2021-06-29 at 14 47 35" src="https://user-images.githubusercontent.com/2459151/123808792-f935d880-d8e8-11eb-8777-e01454bf3c38.png">

Screenreader and keyboard only users are able to focus on the close button. This needs to be unavailable until users click on the "Read" button. This can be done by applying `display: none` to the modal. The modal also requires the following attributes `role="dialog" aria-modal="true`. This prevents being able to navigate to content behind the modal until it is closed.

**Comment by kingdomlevel** [comment]
Fix to the Dashboard page - relies on #209 being merged before it can be fixed.

**Comment by kingdomlevel** [comment]
PR #209 has now been merged - removing the 'blocked' label and moving to 'To Do'

**Comment by UsmanAfzal** [comment]
Checked and approved
