### ISSUE TITLE
[modal] close button uses the character "x"

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/OR-UK-frontend#189]
URL: https://openreferraluk.org/dashboard

The modal close button has an "x" as text. This would be more accessible if it simply said "close" or include a visibly hidden span tag with the word "close"

<img width="652" alt="Screenshot 2021-06-29 at 14 47 35" src="https://user-images.githubusercontent.com/2459151/124400046-8e850280-dd17-11eb-9473-f548d36679e3.png">

**Comment by kingdomlevel** [comment]
Depends on #209 as it's a dashboard fix

**Comment by kingdomlevel** [comment]
PR #209 has now been merged - removing the 'blocked' label and moving to 'To Do'

**Comment by UsmanAfzal** [comment]
Checked and approved
