### ISSUE TITLE
[buttons] alignment issues with header buttons

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/OR-UK-frontend#192]
URL: https://openreferraluk.org/dashboard

The Forum and For Developer buttons are misaligned less than 1030px and greater than 630px.

<img width="883" alt="Screenshot 2021-07-05 at 01 07 16" src="https://user-images.githubusercontent.com/2459151/124403328-b3847000-dd2d-11eb-852e-6ab40765436f.png">

**Comment by kingdomlevel** [comment]
Depends on #209 being merged before work can be completed.

**Comment by kingdomlevel** [comment]
PR #209 has now been merged - removing the 'blocked' label and moving to 'To Do'

**Comment by UsmanAfzal** [comment]
Checked and approved
