### ISSUE TITLE
[image] alt text required for logo on developer site

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/OR-UK-frontend#195]
URL: https://developers.openreferraluk.org/

Include alt text "Open Referral UK logo" for the logo on the landing page.

<img width="758" alt="Screenshot 2021-07-05 at 01 20 22" src="https://user-images.githubusercontent.com/2459151/124403651-5b4e6d80-dd2f-11eb-8a0f-1db17ac11143.png">

**Comment by PorismDominicSkinner** [comment]
Done

**Comment by UsmanAfzal** [comment]
Checked and approved.
