### ISSUE TITLE
[navigation] No method of users to return to the main website

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/OR-UK-frontend#203]
URL: https://docs.google.com/forms/d/e/1FAIpQLScZU1lVUDZoruKzT86MV1Ko0v7LTBSA9-Y8fd9a-I73-jv2KA/viewform

Registration form for joining the the community.

When users arrive at the form, there is no method of return to the website even, no link present or even once the details have been submitted.

**Comment by kingdomlevel** [comment]
This is not something that can be fixed by the Snook development team at present. It requires access the live Google form which is likely something that Porism have control of.

We should reach out to Porism to see if they have access to the Google form and if they can include a link back to the ORUK website, or if they want to give us access to do it.

**Comment by MikeThacker1** [comment]
As per an earlier issue that Porism took over from Snook, Porism is replacing the Google Form (under the ORUK google Workspace account) with the page https://openreferraluk.org/register 

That page is integrated in the site with full navigation.

This is Porism Jira point https://porism.atlassian.net/browse/ORUK-45 (only visible to Porism people). We'll update here when the new page is swapped in.

**Comment by matt-porism** [comment]
All links have now been updated to point to https://openreferraluk.org/register

**Comment by MikeThacker1** [comment]
We think this issue can now be closed

**Comment by UsmanAfzal** [comment]
@adamgparsons @matt-porism the "Feature your organisation" link on the homepage is still linking to the Google Form.

https://openreferraluk.org

**Comment by MikeThacker1** [comment]
We've fixed this.

**Comment by UsmanAfzal** [comment]
The old registration link as mentioned in the ticket is no longer used and users should not be taken to the Google Form.
