### ISSUE TITLE
[link] Sign up link for newsletter is broken

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/OR-UK-frontend#204]
URL: https://openreferraluk.org/contact-us

The sign up link is broken.

<img width="540" alt="Screenshot 2021-07-05 at 17 14 04" src="https://user-images.githubusercontent.com/2459151/124498571-7b744000-ddb4-11eb-8bdf-7ff8ccac1fc2.png">

**Comment by kingdomlevel** [comment]
CMS fix - working as expected now! 🏆
