### ISSUE TITLE
[Abbreviation] No expansion provided for abbreviation

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/OR-UK-frontend#205]
URL: https://openreferraluk.us1.list-manage.com/subscribe?u=9cdac16b200ed03ca1159653a&id=00056900bd

Abbreviation SSG used without explaining its meaning. Apply expansion prior to the abbreviation (SSG).

<img width="754" alt="Screenshot 2021-07-05 at 17 18 44" src="https://user-images.githubusercontent.com/2459151/124498916-0e14df00-ddb5-11eb-8548-7d2aa840bc71.png">

**Comment by kingdomlevel** [comment]
This is a content fix to copy on ORUK's MailChimp account. It's not something that can be fixed by the Snook development team.

We should reach out to Porism and find out who has access to this account to update this copy.

**Comment by MikeThacker1** [comment]
I've raised this in Porism's Jira system as https://porism.atlassian.net/browse/ORUK-89 (only Porism people have access) to be addressed by Porism's Nick Bryan.

We will remove the field which is no longer relevant.

**Comment by MikeThacker1** [comment]
SSG field has been removed so I consider this case done, but don't think I have permission to close it.

**Comment by UsmanAfzal** [comment]
Checked and approved
