### ISSUE TITLE
[registration] No confirmation for registeration

### ISSUE THREAD

**Issue by UsmanAfzal** [WeAreSnook/OR-UK-frontend#264]
URL: https://openreferraluk.org/register

Users of assistive technologies are given feedback once all fields have been filled and whether they have registered of if the details are already registered.

![Screenshot 2021-07-28 at 21 21 13](https://user-images.githubusercontent.com/2459151/127390699-2016b63a-794a-4cf4-9281-e23e2e747f5d.png)

The example above requires "Registered Successfully" to be read out by screenreaders. Include "aria-live="polite" to resolve.

**Comment by UsmanAfzal** [comment]
@matt-porism

**Comment by matt-porism** [comment]
The success message should now have a aria-live="polite" attribute.

**Comment by UsmanAfzal** [comment]
Thanks @matt-porism checked and approved.
